### ISSUE TITLE
Map suggestion 

### ISSUE THREAD

**Issue by Coxy98** [NessunoNL/21stVikings#10]
http://www.armaholic.com/page.php?id=23869

Fighting in the civilized world would be refreshing.

**Comment by NessunoNL** [comment]
HQ has talked about this suggestion and likes the idea of a city map. However, this map is still in very early alpha and there seem to be many issues with it. Therefore, HQ would like to suggest [Bornholm](http://www.armaholic.com/page.php?id=27056) as an alternative. How do you feel about adding Bornholm?

**Comment by Coxy98** [comment]
The map looks good.It says that the map has narrow cities, which would be fun and interesting to battle in.

Date: Mon, 14 Dec 2015 15:18:44 -0800
