### ISSUE TITLE
Bornholm

### ISSUE THREAD

**Issue by oconnell10** [NessunoNL/21stVikings#21]
Bornholm is a map which has been suggested in the past and I have used in the past. It is a gorgeous map with 
an area of 280 square km 
the island is 20km by 14km 
the terrain is 22km by 22km 
800+ compounds and farms. 
31 cities, villages, and towns 
large open fields, narrow cities, lots of hills and valleys.
It is a 2/3 scale of the actual island of Bornholm Denmark

It would be an amazing fantastic change of scenery from takistan, chernarus, and urals (to be honist kind of bland) environments for a more 1st world area for combat operations and considering it is an island it would be a nice addition considering the new LHD allows us to do amphibious operations without the need to launch from the land.

http://www.armaholic.com/page.php?id=27056

**Comment by NessunoNL** [comment]
I'll connect this to #10 which we'll discuss next meeting too!
