### ISSUE TITLE
UAV camera shake

### ISSUE THREAD

**Issue by slothinator** [NessunoNL/21stVikings#9]
So basically there is a ton of camera shake, this is a bug within the engine of what i have read but hopefully there would be a fix for it cause the shake make it almost impossible to spot what type of enemies/vehicles you are looking at, u cant tell the difference between a civ or a isis member with aks and stuff.

**Comment by NessunoNL** [comment]
What @slothinator found somewhere on the interwebs: 

>I have been playing alot recently on your public ArmA 3 server and my favorite role by far is that of >Deathstar, the UAV operator.  Overall its alot of fun.  However, I have noticed a bug with the game >itself in regards to the camera shake.  When flying anywhere above 500m with the Greyhawk using >the turret will cause the camera to shake like crazy.  Doing some research this is a known bug with >ArmA 3 and has yet to be fixed.  That being said there is a workaround that I found at {LINK >REMOVED} .  Basicly it involves disabling camera shake on the server.  I was hoping that this was >something that you could do as it would greatly increase the playability of the UAV operator.  I have >included the text of the fix below...
> 
>Our goal here is to change a value within the server's *.Arma3Profile configuration file.
>
>change this -
>
>CameraShake=1;
>
>to this -
>
>CameraShake=0;
> 
>From what I have read that is the simplest fix to the problem.  I understand that camera shake is a >nice feature to some however it is annoying.  If your unable to disable it for everyone I was hoping >it would be possible to maybe fix it only for the UAV operator role. 
> 
>Thanks so much for considering this request!

Implementing this fix would mean that camerashake would just not be allowed on our server. This seems kind of a drastic option so I would like other people to test this issue to check if it appears for everyone. If that is true then HQ will discuss the proposed fix. In that event I would personally suggest to test the fix for one (mini)op and see if any problems arise.

**Comment by slothinator** [comment]
this is a issue for everyone, doesn't matter what drone it is.

**Comment by NessunoNL** [comment]
@slothinator I mean that so far you are the only one that has reported this problem so I would like to know if other people have this too, or that it might be a problem with just your client.

**Comment by slothinator** [comment]
well im the sorta the only one who use the drone, doesn't matter if i play
singelplayer or moltiplayer. i have been looking at videos and reading and
this is a problem for all UAV operators even the ones who made the apex
drakon say this is a problem and you can see it in there tutorial video.

2015-12-06 18:18 GMT+01:00 NessunoNL <notifications@github.com>:

**Comment by NessunoNL** [comment]
[Good News](http://feedback.arma3.com/view.php?id=22394). It seems that BIS have acknowledged this bug and fixed it in their dev release which means that the fix will probably be in the next stable release too.

**Comment by slothinator** [comment]
dang it i need to wait for the next bloody patch, darnit

2015-12-09 18:22 GMT+01:00 NessunoNL <notifications@github.com>:

**Comment by slothinator** [comment]
Yay, Nessuno the savior ;)

2015-12-09 18:49 GMT+01:00 NessunoNL <notifications@github.com>:

**Comment by NessunoNL** [comment]
HQ has talked about this and has decided to wait until BIS fixes this issue, rather than fucking around in the server files and removing a function completely. Sorry Sloth!
